spring:
  profiles:
    active:
    - dev
---
server:
  port: 8003
spring:
  application:
    name: PRODUCT-SERVICE
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/aigou
    username: root
    password: root
  profiles: dev
mybatis-plus:
  mapper-locations: classpath:cn/itsource/aigou/mapper/*Mapper.xml
  type-aliases-package: cn.itsource.aigou.domain,cn.itsource.aigou.query
eureka:
  client:
    service-url:
     defaultZone: http://localhost:7001/eureka
---
server:
  port: 8004
spring:
  application:
    name: PRODUCT-SERVICE-TEST
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/aigou
    username: root
    password: root
  profiles: test
mybatis-plus:
  mapper-locations: classpath:cn/itsource/aigou/mapper/*Mapper.xml
  type-aliases-package: cn.itsource.aigou.domain,cn.itsource.aigou.query
eureka:
  client:
    service-url:
     defaultZone: http://localhost:7001/eureka
